# An example Trunk.toml with all possible fields along with their defaults.

[build]
# The index HTML file to drive the bundling process.
target = "index.html"

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false
